### ISSUE TITLE
Module cordova-plugin-packagemanager.packagemanager does not exist

### ISSUE THREAD

**Issue by justintseng** [fbsanches/cordova-plugin-packagemanager#1]
error

Uncaught SyntaxError: Unexpected token } packagemanager.js:33
Uncaught Error: Module cordova-plugin-packagemanager.packagemanager does not exist. cordova.js:1431

on android 4.4.4

**Comment by cybertim** [comment]
same issue for me, works fine in the emulator tho

**Comment by fbsanches** [comment]
Merge ok, with changes of @cybertim . Thank you

**Comment by fbsanches** [comment]
Solved the problem?

**Comment by cybertim** [comment]
Yes it is solved, but you need to install this plugin with `cordova plugin add https://github.com/fbsanches/cordova-plugin-packagemanager.git` instead of what is in the README.

**Comment by fbsanches** [comment]
Close Issue
